### PR TITLE
Better function call matching (also decorators)

### LINKED ISSUE #16: Built-in types are highlighted as support.function and not support.type if called
Consider the above snippets, `str` is once highlighted as `support.type` and once highlighted as `support.function`, as well as `list`. This is probably because they are actually *used like a function*, but in fact they are classes. The default Python syntax def does not treat these built-in type calls differently to the literal references.

Here is the same snippet with the default Python syntax:

I prefer the default version over the current, but what do you think?

### PR DESCRIPTION
**Pull request by FichteFoll**
As discussed in #16, I finally worked on the function call matching that I already thought of in #8.

Following is a snippet that I used for testing:
```py
list(map(str, range(100)))
[str(i) for i in range(100)]

super(arg1=1)(arg2=2)
list abs, map
some.None NotImplemented

print (file=None) print . __class__
print keyword print __init__

__init__ . something()

callback(print)

.__init__
__init__ [2]


@ deco . __init__ (call=some)  # rator
def function():
    pass
```

Closes #16.

PS: This is unrelated, but there are a couple of `include: $self` occurences that are technically incorrect because in most of these cases only an expression is allowed. However, the snytax def itself is not grouped into statement vs expression, so the grouping would be a required step for this (and would also add more structure).

### CODE REVIEW

**Comment by FichteFoll** [comment]
Saw that you made some changes and fixed an annoying regression with `from . import` statements.

**Comment by MattDMo** [comment]
@FichteFoll sorry for the huge delay, but I'm finally getting around to thinking about releasing PythonImproved 2.0, and I've incorporated a lot of your changes from this PR into [`PythonImproved-Unicode.YAML-tmLanguage`](https://github.com/MattDMo/PythonImproved/blob/unicode/PythonImproved-Unicode.YAML-tmLanguage) in the `unicode` branch. However, right off the bat, I've noticed an issue with [`meta.dotted-name.python`](https://github.com/MattDMo/PythonImproved/blob/unicode/PythonImproved-Unicode.YAML-tmLanguage#L581-L583) &mdash; it's being applied to all `meta.identifier.python` scopes. If I comment out [line 583](https://github.com/MattDMo/PythonImproved/blob/unicode/PythonImproved-Unicode.YAML-tmLanguage#L583) it doesn't show up in the identifier scope anymore. Thoughts?

**Comment by FichteFoll** [comment]
Well, pretty much everything in Python is a "dotted name" (because I made the dotted part before the last 'undotted' part just optional). `#dotted_name` includes `#generic_names`, which is your `meta.identifier.python`. Note that this is used for "identifier that does not have another special meaning" and does not include the dots. `meta.dotted-name.python` is just the "catch-all" for pretty much all dotted names you'll encounter, including the illegal ones with keywords for example.

This part would look a lot simpler with contexts from sublime-syntax btw.

**Comment by FichteFoll** [comment]
I have the feeling that there are quite a few parts missing which I will look into tomorrow. I'll probably prepare a syntax-test file from my fork and compare that to your unicode branch.

**Comment by MattDMo** [comment]
OK, thanks. I'm hoping to release 2.0 by Sunday at the latest (probably quickly followed by 2.0.1, etc.) to coincide with the release of Python 3.5. After that we can talk about making a `.sublime-syntax` version.

**Comment by FichteFoll** [comment]
I prepared a syntax test file from my previously used test file and pushed it to the branch.

Notable issues (visible in testfile):

1. The actual reason why I made the PR in the first place (#16): types are matched as functions instead of types when used in function calls
2. Built-in functions are only matched when used in a function call and not when used as a callback parameter for example
3. `Ellipsis` and `NotImplemented` should not be matched as attributes
4. parameters for magic function calls do not get highlighted
5. `print` matched as `invalid` in several places where it is valid, just as a function
6. allcaps constants not matched in attribtue access from results from function calls
7. decorators with spaces fail deliberately
8. decorators only have the initial name highlighted as `entity.name.function.decorator` (which is imo the wrong scope anyway) and do not continue over the entire decorator call, if there is one. This is actually wrong in my version too, but at least consistent

So yeah, it's probably 80% of my work that's still missing.

I honestly do not feel like revisiting this again. You just took too long to merge the changes I made and made too many changes on the main and unicode branch in the meantime so that merging will be a hassle.

Instead, I will most likely work on a new `Python.sublime-syntax` version from scratch, while taking some inspiration from my fork. There are a couple of things where contexts would be way easier than this.

**Comment by MattDMo** [comment]
I'm going to close this, mainly for the reasons you mentioned above - it's no longer mergeable, and things have just moved on. I think working on a `.sublime-syntax` version is a great idea, although the audience will be somewhat limited due to the fact that the new format isn't supported yet in the public beta. (Speaking of which, any word from Jon on when development is going to start up again?).

I've started #54 to track `.sublime-syntax` work, and I'll be making a new branch soon.

**Comment by FichteFoll** [comment]
>(Speaking of which, any word from Jon on when development is going to start up again?)

None that I know of, sadly.

I made a pretty nice YAML syntax definition and submitted it to the packages repo (https://github.com/sublimehq/Packages/pull/90) 4 months ago, but no word since. My end goal would be to have a neutral comprehensive and accurate Python.sublime-syntax that was bundled with Sublime Text by default, but so far I'm hesitant due to the lack of updates.
As you mentioned, `.sublime-syntax` is still a dev-only feature and I'd rather spend my time on plugins for all people (on ST3) rather than just the ones on dev. There are numerous ways for me do to that.

**Comment by MattDMo** [comment]
Definitely understandable. I'll work on it now and again just to learn how the format works, but I'm certainly not expecting a rush effort on PI to push it out the door.

**Comment by facelessuser** [comment]
> sublimehq/Packages#90

Nice, I didn't know about this.  I will have to try it out.

**Pull request closed without merging**
